[isas]
command=/mnt/speedstorage/ISAS_TOOL/isas_f90/OA_main

[series]
first_y = 1960
last_y = 1989
first_m = 1
last_m = 12
first_bassin = 1
last_bassin = 5
first_box = 1
last_box = 99

[path]
log=log
data=data
tmp=tmp

[config]
param = PSAL

clim = /mnt/speedstorage/CORA/CLIM//ISAS17_DMFD_CLIM_ann_STD_PSAL.nc
cov = /mnt/speedstorage/CORA/CLIM//ISAS15_DMFD_ann_0_COVS.nc
bathy = /mnt/speedstorage/CORA/CLIM//bathy_isas17.nc 
; covar_ls  x, y t (in km, km, days)
covar_ls_x = 300
covar_ls_y = 300
covar_ls_t = 30
; covar_ms_t (in days)
covar_ms_t = 20
; var_weigh (LS, MS, UR)
var_weigh_ls = 1
var_weigh_ms = 2
var_weigh_ur = 8
; x, y, z, t covariance dependency (1 = yes, 0 = no)
cd_x = 1
cd_y = 1
cd_z = 0
cd_t = 1
; fact. Variance (former 1.5) 
variance = 5  
; QC Max   Mx_std
qc_max = 5
mx_std = 15
; Cov_max (if > 1, no oversampling test)
cov_max = 0.99
